# -*- coding: utf-8 -*-

ESTADOS = { 
	'': '',
	'AGUASCALIENTES': 'AS',
	'BAJA CALIFORNIA': 'BC',
	'BAJA CALIFORNIA SUR': 'BS',
	'CAMPECHE': 'CC', 
	'CHIAPAS': 'CS',
	'CHIHUAHUA': 'CH',
	'COAHUILA': 'CL',
	'COLIMA': 'CM',
	'DISTRITO FEDERAL': 'DF',
	'DURANGO': 'DG',
	'GUANAJUATO': 'GT',
	'GUERRERO': 'GR',
	'HIDALGO': 'HG',
	'JALISCO': 'JC',
	'MEXICO': 'MC',
	'MICHOACAN': 'MN',
	'MORELOS': 'MS',
	'NAYARIT': 'NT',
	'NUEVO LEON':'NL',
	'OAXACA': 'OC',
	'PUEBLA': 'PL',
	'QUERETARO': 'QT',
	'QUINTANA ROO': 'QR',
	'SAN LUIS POTOSI': 'SP',
	'SINALOA': 'SL', 
	'SONORA': 'SR',
	'TABASCO': 'TC',
	'TAMAULIPAS': 'TS',
	'TLAXCALA': 'TL',
	'VERACRUZ': 'VZ',
	'YUCATÁN': 'YN',
	'ZACATECAS': 'ZS',
	'NACIDO EXTRANJERO': 'NE'
}

OBSCENAS = ['BUEI', 'BUEY', 'CACA', 'CACO', 'CAGA', 'CAGO', 'CAKA', 'CAKO',
			'COGE', 'COGI', 'COJA', 'COJE', 'COJI', 'COJO', 'COLA', 'CULO',
			'FALO', 'FETO', 'GETA', 'GUEI', 'GUEY', 'JETA', 'JOTO', 'KACA',
			'KACO', 'KAGA', 'KAGO', 'KAKA', 'KAKO', 'KOGE', 'KOGI', 'KOJA',
			'KOJE', 'KOJI', 'KOJO', 'KOLA', 'KULO', 'LILO', 'LOCA', 'LOCO',
			'LOKA', 'LOKO', 'MAME', 'MAMO', 'MEAR', 'MEAS', 'MEON', 'MIAR',
			'MION', 'MOCO', 'MOKO', 'MULA', 'MULO', 'NACA', 'NACO', 'PEDA',
			'PEDO', 'PENE', 'PIPI', 'PITO', 'POPO', 'PUTA', 'PUTO', 'QULO',
			'RATA', 'ROBA', 'ROBE', 'ROBO', 'RUIN', 'SENO', 'TETA', 'VUEI', 
			'VUEY', 'WUEI', 'WUEY']
			